version: '3'

services:
        mysql-dev:
                image: mysql:8.0.2
                environment:
                        MYSQL_ROOT_PASSWORD: password
                        MYSQL_DATABASE: imgapp
                ports:
                        - "3308:3306"
                volumes:
                        - "./data:/var/lib/mysql:rw"
        adminer:
               image: adminer
               restart: always
               ports:
                    - 8080:8080
